spring.application.name=${SPRING_APPLICATION_NAME:Foreman_Backend}

#Server port
server.port=${PORT:8080}
server.forward-headers-strategy=framework

#DB Config
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/foreman_backend?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:9433}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#JWT Config
jwt.secret=${JWT_SECRET_KEY:SECRETKEY262132262188BIGASSCREATEDINJULY252020}
jwt.expiration=${JWT_EXPIRATION_MS:86400000}

#Frontend details
app.frontend-domain=${APP_FRONTEND_DOMAIN:https://foreman-project.netlify.app}

#Notification microservice details
notification.service.url=${NOTIFICATION_SERVICE_URL:http://localhost:5092}
